---
# Source: work-order-form/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: work-order-form-dev
  labels:
    app: work-order-form
    chart: work-order-form-0.1.21
    release: work-order-form
    heritage: Helm
data:
  API_TARGET_HOSTS: Y2hhbmdlbWU=
  AMPLITUDE_KEY: Y2hhbmdlTWU=
  SKILL_DISCOVERY_SECRET: Y2hhbmdlTWU=
  JWT_SECRET: Y2hhbmdlTWU=
type: Opaque
---
# Source: work-order-form/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: work-order-form-dev
  labels:
    app: work-order-form
    chart: work-order-form-0.1.21
    release: work-order-form
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: work-order-form
  selector:
    app: work-order-form
    release: work-order-form
---
---
# Source: work-order-form/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-order-form-dev
  labels:
    app: work-order-form
    chart: work-order-form-0.1.21
    release: work-order-form
    heritage: Helm
    fieldnation.com/name: work-order-form
    fieldnation.com/env: dev
    fieldnation.com/version: master
    fieldnation.com/managed-by: provider-reputation
    fieldnation.com/pod-type: server
    tags.datadoghq.com/env: dev
    tags.datadoghq.com/service: work-order-form
    tags.datadoghq.com/version: master

spec:
  replicas: 1
  selector:
    matchLabels:
      app: work-order-form
      release: work-order-form
  template:
    metadata:
      labels:
        app: work-order-form
        release: work-order-form
        fieldnation.com/name: work-order-form
        fieldnation.com/env: dev
        fieldnation.com/version: master
        fieldnation.com/managed-by: provider-reputation
        fieldnation.com/pod-type: server
        tags.datadoghq.com/env: dev
        tags.datadoghq.com/service: work-order-form
        tags.datadoghq.com/version: master
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
        iam.amazonaws.com/role: changeMe
    spec:
      containers:
        - name: work-order-form
          
          image: "197309122981.dkr.ecr.us-west-2.amazonaws.com/work-order-form:master"
          
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: API_TARGET_HOSTS
              valueFrom:
                secretKeyRef:
                  key: API_TARGET_HOSTS
                  name: work-order-form-dev
            - name: AWS_S3_BUCKET_NAME
              value: "changeMe"
            - name: CDN
              value: "changeMe"
            - name: CONTEXT_COLUMNS
              value: ""
            - name: QUALIFICATIONS_URL
              value: "changeMe"
            - name: WORK_ORDER_AUTO_APPROVE_URL
              value: "changeMe"
            - name: API_URL
              value: "changeMe"
            - name: AMPLITUDE_KEY
              valueFrom:
                 secretKeyRef:
                   key: AMPLITUDE_KEY
                   name: work-order-form-dev
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APM_PROVIDER
              value: "changeme"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "false"
            - name: SKILL_DISCOVERY_URL
              value: ""
            - name: SKILL_DISCOVERY_SECRET
              valueFrom:
                 secretKeyRef:
                   key: SKILL_DISCOVERY_SECRET
                   name: work-order-form-dev
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: work-order-form-dev
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 25
            timeoutSeconds: 3
            failureThreshold: 2
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 25
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 358Mi
             
